# TRUNCATE : TO DELETE WHOLE DATA IN TABLE NOT DELETE TABLE.
#(IF WE USE DROP THEN DELETE WHOLE TABLE WITH DATA)

USE COLLEGE;

CREATE TABLE STUDENT (
    ROLLNO INT PRIMARY KEY,
    NAME VARCHAR(50),
    MARKS INT NOT NULL,
    GRADE VARCHAR(1),
    CITY VARCHAR(20)
);

INSERT INTO STUDENT (ROLLNO,NAME,MARKS,GRADE,CITY) 
VALUES
(101,"ASHWINI",20,"A","PUNE"),
(102,"YASH",18,"C","MUMBAI"),
(103,"VAIDEHI",21,"B","PUNE"),
(104,"RUPALI",25,"A","DELHI"),
(105,"MOHAN",26,"B","PUNE"),
(106,"ROHAN",22,"A","MUMBAI");

SELECT * FROM STUDENT;
TRUNCATE TABLE STUDENT;
SELECT * FROM STUDENT;



-- PRACTICE: 

#CHANGE COL NAME:
ALTER TABLE STUDENT 
CHANGE NAME FULLNAME VARCHAR(50);

#DELETE DATA SPECIFIC
INSERT INTO STUDENT (ROLLNO,FULLNAME,MARKS,GRADE,CITY) 
VALUES
(101,"ASHWINI",20,"A","PUNE"),
(102,"YASH",18,"C","MUMBAI"),
(103,"VAIDEHI",21,"B","PUNE"),
(104,"RUPALI",25,"A","DELHI"),
(105,"MOHAN",26,"B","PUNE"),
(106,"ROHAN",22,"A","MUMBAI");

DELETE FROM STUDENT
WHERE MARKS <20;
SELECT * FROM STUDENT;



# indexes
-- This command will show you both the PRIMARY index and the 'idx_city' index

SHOW INDEX FROM STUDENT;   #SHOWS INDEX
SELECT* FROM STUDENT;

-- If you have already renamed the column to FULLNAME:
CREATE INDEX idx_name ON STUDENT(NAME);
 
 -- INDEXS CONSUME DESK SPACE. ITS SLOW DOWN INSERT ,UPDATE, DELETE OPERATIONS, SO DONT CREATE INDEXES ON ALL COLIUMNS .
