-- ALTER  : TO CHANGE THE SCHEMA
#ADD
#RENAME
#DROP

USE COLLEGE;

CREATE TABLE STUDENT (
    ROLLNO INT PRIMARY KEY,
    NAME VARCHAR(50),
    MARKS INT NOT NULL,
    GRADE VARCHAR(1),
    CITY VARCHAR(20)
);

INSERT INTO STUDENT (ROLLNO,NAME,MARKS,GRADE,CITY) 
VALUES
(101,"ASHWINI",20,"A","PUNE"),
(102,"YASH",18,"C","MUMBAI"),
(103,"VAIDEHI",21,"B","PUNE"),
(104,"RUPALI",25,"A","DELHI"),
(105,"MOHAN",26,"B","PUNE"),
(106,"ROHAN",22,"A","MUMBAI");

SELECT * FROM STUDENT;

# ADD COLUMN: ADD COLUMN IN TABLE
ALTER TABLE STUDENT
ADD COLUMN AGE INT NOT NULL DEFAULT 20;
SELECT * FROM STUDENT;


# DROP COLUMN
ALTER TABLE STUDENT
DROP COLUMN AGE;
SELECT * FROM STUDENT;


#RENAME TABLE
ALTER TABLE STUDENT
RENAME TO STU;
SELECT * FROM STU;


# CHANGE COLUMN NAME(RENAME)
ALTER TABLE STU
ADD COLUMN AGEE INT;

ALTER TABLE STU
CHANGE COLUMN AGEE AGE INT;
SELECT * FROM STU;


# MODIFY COLUMN (MODIFY DATA TYPE/CONSTRAINT)
ALTER TABLE STU
MODIFY AGE VARCHAR(2);



