-- Create tables with cascading rules:
# FOREIGN KEY

# CASCADING FOR FK:  (IF CHANGE IN ONE TABLE CHANGE ALSO ANOTHER TABLE CALLED CASCADING)
#(IF CHANGES LIKE UPDATION OR DELETION DONE IN PARENT TABLE ALSO DISPLAY IN CHILD TABLE.)

# ON DELETE CASCADE
# ON UPDATE CASCADE

USE COLLEGE;

CREATE TABLE DEPT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50)
);

CREATE TABLE TEACHER (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID) REFERENCES DEPT(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

-- Insert sample data
INSERT INTO DEPT 
VALUES
(101, 'ENGLISH'), 
(102, 'MARATHI');

INSERT INTO TEACHER
VALUES
(101, 'ASHWINI', 101),
(102, 'VAIDEHI', 102);

-- Perform the update (Cascading will work now)
UPDATE DEPT 
SET ID = 103
WHERE ID = 102;

-- Verify results
SELECT * FROM DEPT;
SELECT * FROM TEACHER;
