SHOW DATABASES;  

CREATE DATABASE TEMP1;
CREATE DATABASE TEMP2;
SHOW DATABASES;

DROP DATABASE TEMP1;
DROP DATABASE TEMP2;
SHOW DATABASES;

CREATE DATABASE college;
SHOW DATABASES;
USE college;
CREATE TABLE student(
   id INT PRIMARY KEY,
   name VARCHAR(50),
   age INT NOT NULL
);

INSERT INTO student VALUES(1,"ASHWINI",20);
INSERT INTO student VALUES(2,"VAIDEHI",21);

SELECT * FROM student;