# DAY 3 : CONSTRAINTS- RULES FOR DATA IN TABLE.

# 1. UNIQUE
# 2. PRIMARY KEY
# 3. NOT NULL

SHOW DATABASES;  
USE college;

#PARENT TABLE

CREATE TABLE TEMP1(
ID INT UNIQUE NOT NULL,
NAME VARCHAR(50),
PRIMARY KEY(ID,NAME)
);
INSERT INTO TEMP1 VALUES (101,"ASHWINI");
INSERT INTO TEMP1 VALUES (102,"YASH");
SELECT * FROM TEMP1;


# 4. FOREIGN KEY
# 5. DEFAULT

#CHILD TABLE

CREATE TABLE TEMP2(
CUST_ID INT PRIMARY KEY,
SALARY INT DEFAULT 2000,
FOREIGN KEY(CUST_ID)
REFERENCES TEMP1(ID)      
);                                      #COLUM LINK TO TEMP1

INSERT INTO TEMP2 VALUES (101,5000);    
INSERT INTO TEMP2 (CUST_ID) VALUES (102);    # BYDEFAULT GIVES SALARY 2000.

INSERT INTO TEMP2 VALUES (103,2000);    # NOT INSERT IN TEMP TO CAUSE 103 NOT IN TEMP1

SELECT * FROM TEMP2;



# 6.CHECK:LIMIT THE VALUES

CREATE TABLE CITY(
ID INT PRIMARY KEY,
CITY VARCHAR(50),
AGE INT,
CONSTRAINT AGE_CHECK CHECK(AGE>=18 AND CITY="DELHI")
);

INSERT INTO CITY VALUES(1,"DELHI",20);
INSERT INTO CITY VALUES(2,"PUNE",22);    #GIVES ERROR
SELECT * FROM CITY;
