#SELECT IN DETAIL

CREATE DATABASE COLLEGE;
USE COLLEGE;

CREATE TABLE STUDENT(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);

INSERT INTO STUDENT (ROLLNO,NAME,MARKS,GRADE,CITY) 
VALUES
(101,"ASHWINI",20,"A","PUNE"),
(102,"YASH",18,"C","MUMBAI"),
(103,"VAIDEHI",21,"B","PUNE"),
(104,"RUPALI",25,"A","DELHI"),
(105,"MOHAN",26,"B","PUNE"),
(106,"ROHAN",22,"A","MUMBAI");

SELECT * FROM STUDENT;                  #SHOW ALL TABLE

SELECT NAME,MARKS FROM STUDENT;         #SHOW ONLY TWO COLUMN
SELECT CITY FROM STUDENT;               #ONLY CITY COLUMN

SELECT DISTINCT CITY FROM STUDENT;      #UNIQUE CITY ,NOT REPEATE


#WHERE

SELECT * FROM STUDENT WHERE MARKS>21;
SELECT * FROM STUDENT WHERE CITY="PUNE";

#OPERATOR
#1.ARITHMATIC  :+ , -,  *,  /,  %(REMINDER)
#2.COMPARISION :=,  !=,  >,  <,  >=,  <=
#3.LOGICAL     :AND, OR, NOT, IN, BETWEEN, ALL, LIKE, ANY
#4.BITWISE     :&(BITWISE AND), | (BITWISE OR)

SELECT * FROM STUDENT WHERE MARKS>21 AND  MARKS<90;
SELECT * FROM STUDENT WHERE MARKS+10>100;
SELECT * FROM STUDENT WHERE MARKS=93;
SELECT * FROM STUDENT WHERE MARKS!=0;
SELECT * FROM STUDENT WHERE MARKS BETWEEN 80 AND 90;
SELECT * FROM STUDENT WHERE CITY IN ("PUNE");
SELECT * FROM STUDENT WHERE CITY NOT IN ("PUNE");