# CLAUSES
# LIMIT Clause: set an upper limit on tuples/rows to be return.

SHOW DATABASES;
USE COLLEGE;
SHOW TABLES;

SELECT * FROM STUDENT LIMIT 2;     #GIVES 2 ROWS ONLY

SELECT ROLLNO,NAME FROM STUDENT LIMIT 3;


# ORDER BY CLAUSE : TO SORT ACCORDING TO ACCENDING (ASC) OR DESCENDING (DESC)

SELECT * FROM STUDENT ORDER BY CITY ASC;
SELECT ROLLNO,NAME FROM STUDENT ORDER BY ROLLNO,NAME ASC;
SELECT * FROM STUDENT ORDER BY MARKS ASC;
SELECT * FROM STUDENT ORDER BY MARKS DESC LIMIT 3;



#AGGREGATE FUNCTION :PERFORM CAL ON SET VALUES AND RETURN SINGLE value
# COUNT()  MAX()  MIN()  SUM()  AVG()

SELECT MAX(MARKS) FROM STUDENT;
SELECT AVG(MARKS) FROM STUDENT;
SELECT MIN(MARKS) FROM STUDENT;
SELECT COUNT(MARKS) FROM STUDENT;
SELECT SUM(MARKS) FROM STUDENT;


#GROUP BY CLAUSE : GROUPS ROWS,THAT HAVE SAME VALUES,INTO SUMMARY ROWS.
# IT COLLECT DATA FROM  MULTIPLE RECORDS AND GROUPS THE RESULT BY ONE OR MORE COLLUM(WE USE MOSTLY WITH AGGREGATE FUNTION)

SELECT CITY FROM STUDENT
GROUP BY CITY;

SELECT CITY, COUNT(NAME) FROM STUDENT
GROUP BY CITY;

SELECT CITY, AVG(MARKS) FROM STUDENT
GROUP BY CITY;

SELECT CITY,NAME, COUNT(ROLLNO) FROM STUDENT
GROUP BY CITY,NAME;


# HAVING CLAUSE: ~TO WHERE ,APPLIED CONDITIONS ON ROWS AFTER GROUP.

SELECT COUNT(NAME),CITY FROM STUDENT
GROUP BY CITY
HAVING MAX(MARKS)>90;


# GENERAL ORDER/SEQUENCE

#SELECT COLOUMS(S)
#FROM TABLE_NAME
#WHERE CONDITION
#GROUP BY COLUMN(S)
#HAVING CONDITION
#ORDER BY COLUMNS(ASC & DESC)

SELECT CITY 
FROM STUDENT
WHERE GRADE="A"
GROUP BY CITY
HAVING MAX(MARKS)>=93
ORDER BY CITY ASC;
