# JOINS: USE TO COMBINE ROWS FROM TWO OR MORE TABLES 

-- INNER JOIN:(commmon data) return records that have matching values in both tables.

-- OUTER JOIN:
   #LEFT JOIN:  
   #RIGHT JOIN:
   #FULL JOIN:

 USE COLLEGE;
 
 CREATE TABLE STUDENT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50)
);

INSERT INTO STUDENT(ID,NAME)
VALUES
(101,"ASHWINI"),
(102,"YASH"),
(103,"MOHAN");

SELECT * FROM STUDENT;


 CREATE TABLE COURSE (
    ID INT PRIMARY KEY,
    COURSE VARCHAR(50)
);

INSERT INTO COURSE(ID,COURSE)
VALUES
(101,"ENGLISH"),
(105,"MATH"),
(103,"SCIENCE"),
(107,"CS");

SELECT * FROM COURSE;


# ALIAS : ALTERNATIVE NAME (AS S)( NOT UPDATE BOTH CAN USE OR WORK)

# INNER JOIN: COMMON DATA IN BOTH TABLE

SELECT * FROM STUDENT INNER JOIN COURSE 
ON STUDENT.ID=COURSE.ID;


#OUTER JOIN:(EG:LEFT JOIN/LEFT OUTER JOIN BOTH SAME)(YOU CAN WRITE WITH (LEFT OR RIGHT) OR NOT WRITE NOTHING CHANGE.)

#LEFT JOIN:RETURN ALL DATA FROM LEFT TABLE WITH RIGHT MATCHED DATA
SELECT * FROM STUDENT AS S LEFT JOIN COURSE AS C
ON S.ID=C.ID;


#RIGHT JOIN

SELECT * FROM STUDENT RIGHT OUTER JOIN COURSE 
ON STUDENT.ID=COURSE.ID;


#FULL JOIN: RETURN ALL RECORDS. SIMULATED USING LEFT JOIN, RIGHT JOIN, AND UNION

SELECT * FROM STUDENT LEFT JOIN COURSE 
ON STUDENT.ID=COURSE.ID
UNION
SELECT * FROM STUDENT RIGHT JOIN COURSE 
ON STUDENT.ID=COURSE.ID;


# CROSS JOIN: COMBINES EVERY ROW OF LEFT TABLE WITH EVERY ROW OF RIGHT TABLE

SELECT * FROM STUDENT 
CROSS JOIN COURSE;


# SELF JOIN: JOINS THE SAME TABLE WITH ITSELF USING ALIASES  (EXAMPLE: FINDING ALL POSSIBLE PAIRS OF DIFFERENT STUDENTS FOR A PROJECT)
# EXAMPLE: PAIRING EVERY STUDENT WITH EVERY OTHER STUDENT FOR A GROUP PROJECT

CREATE TABLE T1 (
    NAME VARCHAR(50)
);
INSERT INTO T1(NAME)
VALUES
("ASHWINI"),
("YASH");
SELECT * FROM T1;


CREATE TABLE T2 (
    NAME VARCHAR(50)
);
INSERT INTO T2(NAME)
VALUES
("MOHAN"),
("RUPALI");
SELECT * FROM T2;

SELECT T1.NAME, T2.NAME 
FROM T1 JOIN T2
ON T1.NAME <> T2.NAME;


#ON OLD TABLE
SELECT S1.NAME, S2.NAME 
FROM STUDENT AS S1
INNER JOIN STUDENT AS S2 
ON S1.ID <>   S2.ID;


#LEFT EXCLESIVE JOIN

SELECT * FROM STUDENT LEFT JOIN COURSE 
ON STUDENT.ID=COURSE.ID
WHERE COURSE.ID IS NULL;


#RIGHT EXCLUSIVE

SELECT * FROM STUDENT RIGHT JOIN COURSE 
ON STUDENT.ID=COURSE.ID   
WHERE STUDENT.ID IS NULL;


#UNION:UNIQUE

SELECT NAME FROM T1
UNION 
SELECT NAME FROM T2;

#UNION ALL: ALL WITH DUPLICATE

SELECT NAME FROM T1
UNION ALL
SELECT NAME FROM T2;
