#TABLE REALTED QUESRIES:
#TO UPDATE ROW (TO CHANGE VALUES MULTIPLE TIME AT ONCE)

SHOW DATABASES;
USE COLLEGE;
SHOW TABLES;
SELECT * FROM STUDENT;

#SAFE MODE:TO SAVE FROM ANY UNWANTED CHANGES.(TO OFF THIS WE USE THIS(WE MAKE IT 0 TO OFF))
SET SQL_SAFE_UPDATES= 0;   

UPDATE STUDENT 
SET GRADE = "O"
WHERE GRADE = "A";

UPDATE STUDENT 
SET MARKS = 30
WHERE ROLLNO = 101;

UPDATE STUDENT 
SET GRADE = "B"
WHERE MARKS>80;

UPDATE STUDENT 
SET MARKS = MARKS+1;
SELECT* FROM STUDENT;


#DELETE FROM STUDENT;  ----REMOVE ALL DATA IN TABLE

DELETE FROM STUDENT WHERE MARKS <20;
SELECT* FROM STUDENT;
