#SUB QUERIES / INNER QUERY / NESTED QUERY :QUERY INSIDE ANOTHER QUERY (USING THREE WAYS AS FOLLOW)

#SELECT
#FROM
#WHERE

USE COLLEGE;

CREATE TABLE STUDENT (
    ROLLNO INT PRIMARY KEY,
    NAME VARCHAR(50),
    MARKS INT NOT NULL
);

INSERT INTO STUDENT (ROLLNO,NAME,MARKS) 
VALUES
(101,"ASHWINI",20),
(102,"YASH",18),
(103,"VAIDEHI",21),
(104,"RUPALI",25),
(105,"MOHAN",26),
(106,"ROHAN",22);
SELECT * FROM STUDENT;

-- 1.
SELECT AVG(MARKS) FROM STUDENT;

SELECT NAME,MARKS FROM STUDENT 
WHERE MARKS>20;

SELECT NAME,MARKS FROM STUDENT 
WHERE 
MARKS > (SELECT AVG(MARKS) FROM STUDENT);



-- 2.
SELECT ROLLNO FROM STUDENT
WHERE ROLLNO % 2=0;

SELECT NAME,ROLLNO FROM STUDENT
WHERE ROLLNO IN (102,104,106);

SELECT NAME,ROLLNO FROM STUDENT
WHERE 
ROLLNO IN (SELECT ROLLNO FROM STUDENT WHERE ROLLNO % 2=0);



-- 3
ALTER TABLE STUDENT
ADD COLUMN CITY VARCHAR(20) NOT NULL;
SELECT * FROM STUDENT;


UPDATE STUDENT SET CITY = 'PUNE' WHERE ROLLNO = 101;
UPDATE STUDENT SET CITY = 'MUMBAI' WHERE ROLLNO = 102;
UPDATE STUDENT SET CITY = 'DELHI' WHERE ROLLNO = 103;
UPDATE STUDENT SET CITY = 'PUNE' WHERE ROLLNO = 104;
UPDATE STUDENT SET CITY = 'BANGALORE' WHERE ROLLNO = 105;
UPDATE STUDENT SET CITY = 'MUMBAI' WHERE ROLLNO = 106;

SELECT MAX(MARKS)
FROM (SELECT * FROM STUDENT WHERE CITY ="PUNE") AS TEMP;

# OR

SELECT MAX(MARKS) FROM STUDENT
WHERE CITY ="PUNE";


SELECT NAME, MARKS FROM STUDENT 
WHERE
CITY = 'PUNE' AND MARKS = (SELECT MAX(MARKS) FROM STUDENT WHERE CITY = 'PUNE');




# VIEWS :CREATE TEMP TABLE OR VIRTUAL TABLE (SMALL SPECIFICK DATA FROM LARGE TABLE)

CREATE VIEW V1 AS 
SELECT ROLLNO , NAME FROM STUDENT;

SELECT * FROM V1;
DROP VIEW V1;





SET AUTOCOMMIT=0;
COMMIT;
ROLLBACK;

SET SQL_SAFE_UPDATES = 0;

-- Step 1: Turn off automatic saving
SET AUTOCOMMIT=0;

-- Step 2: Make a temporary change (e.g., mistakenly changing Rupali's marks)
UPDATE STUDENT SET MARKS = 0 WHERE NAME = 'RUPALI'; 

-- Verification: If you run SELECT * FROM STUDENT, you will see Rupali's marks as 0.
SELECT * FROM STUDENT;

-- Step 3: Realize the mistake and undo it
ROLLBACK;

-- Result: Rupali's marks are restored back to 25.

-- Step 4: Make a correct change
UPDATE STUDENT SET MARKS = 30 WHERE NAME = 'RUPALI';

-- Step 5: Save the correct change permanently
COMMIT;

-- Result: The marks are now permanently 30. A ROLLBACK now will not change it back.



